### ISSUE TITLE
Debugging Symbols

### ISSUE THREAD

**Issue by MadMockers** [paultech/DASM#13]
Option to output debugging information.

Helpful information could include:
PC <-> Labels
PC <-> Line Numbers
Source code

Could be JSON?

**Comment by interfect** [comment]
We should come up with a DCPU binary object format, with relocation information as well as debugging symbol info.

**Comment by paultech** [comment]
One worth looking at suggested by miles - https://github.com/galaxy-team/asteroid

**Comment by milesrout** [comment]
The Galaxy project has a DCPU binary object format called Asteroid, which is versioned, has the exported labels (label -> pc), used labels (pc, so it's relocatable) and imported labels (pc -> label).

The format is very simple.

**Comment by milesrout** [comment]
The format is null-terminated "GALAXYOBJ" followed by null-terminated "0001", then each of the three maps/arrays I mentioned, followed by the object code itself. Everything except the header is preceded by a length which is a `uint16_t`. 

e.g.

    "GALAXYOBJ"
    "0001"
    0x0003
    "label1"
    0x1F32
    "label1_loop"
    0x1F38
    "label1_break"
    0x1F3e
    0x0001
    0x1F35
    0x0002
    0x1F3a
    "external_call"
    0x1F34
    "other_external_call"

**Comment by interfect** [comment]
I looked at Galaxy, and it seemed perfect *except* that I think its strings
are specified as byte strings and not word strings, which would offset the
whole file by 1/2 word (since GALAXYOBJ has an odd number of letters).

If we take them as word strings (1 word per character) or otherwise pad the
strings to word boundaries, I think it'd probably be the right format to
use.

**Comment by milesrout** [comment]
Yeah currently the asteroid code itself is a rather imperfect representation of the format. It has endianness issues as well (because it doesn't call `ntohs` and `htons` on things before writing them out). 

I'll open an issue on asteroid.

**Comment by Meisaka** [comment]
considering the topic of this issue is "debugging symbols", I find the asteroid format quite lacking in that area, it has no fields for data types (if a high level language supports them), does not include line numbers (from asm and/or compiled languages).
Also, it only appears to support a single block of code which does not include any kind of addresses, where as an assembler can (and will) most likely output multiple blocks intended for different load addresses.
simplicity is nice yes, but the asteroid format needs a few things to provide good debugging info.

**Comment by milesrout** [comment]
>it has no fields for data types

Why would you want fields for data types in an object file format?

>line numbers

As I said to @paultech on IRC, this is asteroid version 1 and it can quite easily be extended.

>single block of code

That's because it's a single object file. It's not for `/bin/foo`, it's for `./build/foo.o` and `./build/bar.o`.

**Comment by paultech** [comment]
Think we need to do a clean spec of what we want in the debugging/object file format. Compatibility with legacy tools is not a priority if we are compromising flexibility of the format to achieve.. If we are increasing the version of the GALAXYOBJ format we'll remove compatibility anyway.

We shall draft a copy of the spec on TC-Specs, once everyone is happy with format we'll move back over to DASM to implement.

**Comment by milesrout** [comment]
It's not about compatibility with legacy tools. It's about the usefulness of the DCPU community standardising on an object file format.

**Comment by Meisaka** [comment]
> Why would you want fields for data types in an object file format?
because standard object formats (like ELF) support this, in addition to load address, assembly address, alignment etc.

**Comment by milesrout** [comment]
"because ELF does it" isn't a good reason. This isn't a format for every CPU under the sun, it's a format for the DCPU-16 and just the DCPU-16.

**Comment by paultech** [comment]
@milesrout there are various different debugger format currently available in the "DCPU Community" picking one arbitrary based on your involvement/recommendation does not make it standardized.  

We will be creating a Spec that includes the functionality that we desire while doing so in a open manner so others may implement if they so desire. We have zero commitment to select from existing formats if they do not provide what we need.  We welcome your input on the new specification if you continue to provide feedback in a constructive and non-combative way.

Thread pruned.  New issue to be opened on TC-Specs.
